### ISSUE TITLE
losing serial connection

### ISSUE THREAD

**Issue by oldbitman-ham** [OpenGammaProject/Open-Gamma-Detector#26]
I am using a MICROFC-30035-SMT-TR because I can't find the 60035.When I turn up the threshold until the red led is mostly on I lose the serial connection. Could this have something to do with the "delay" or "reset" settings? With careful adjustment of threshold and gain I can only get it up to 8 or 9 CPS. With it set here I will lose the serial when I send commands and if I reset or power cycle the serial won't come back until I reduce the threshold.
Any thoughts?

**Comment by Phoenix1747** [comment]
Hi,
you're actually not supposed to have the LED mostly **on**, it should be the exact opposite (mostly **off**)! You're probably just saturating the device with noise. If you set it so that you can only see some very faint blinking then the device shouldn't die anymore. Depending on the cps you are reading then, you can play with the threshold again.

**Comment by oldbitman-ham** [comment]
Thanks for the info, I was reading the instructions wrong. I am also finding that setting reset, averaging and delay have a huge effect. This is a very steep learning curve. Also should I use calibration in Gamma MCA app to set it to known sources?

**Comment by Phoenix1747** [comment]
> I am also finding that setting reset, averaging and delay have a huge effect. This is a very steep learning curve.

If it works with the default settings, you don't need to change it. I would especially recommend leaving the auto reset on to deal with noise. The other settings are not too important if you're using the MICROFC-30035-SMT-TR SiPM anyways.

> Also should I use calibration in Gamma MCA app to set it to known sources?

Yes.

**Comment by Phoenix1747** [comment]
Closing this as your serial connection issues seem to be resolved for now.
