### ISSUE TITLE
Recommended size for scintilattion crystal?

### ISSUE THREAD

**Issue by GhostDog98** [OpenGammaProject/Open-Gamma-Detector#42]
I've identified what I believe to be a fairly decent deal for a Nal(Ti) crystal, which is 25mmx25mm.
I'd want to be able to identify isotopes with a fair amount of certainty, but I cannot find any information about how the crystal size affects the reading accuracy, apart from the obvious limitation of isotope size that I can easily sample.

Would it be simply the case that I may just need to sample my isotope for longer due to the decreased area of the crystal?
Additionally, would discoloration and spots on the crystal affect the results of my gamma spectroscopy much?

Cheers for your advice,
Ghostoverflow

**Comment by NuclearPhoenixx** [comment]
> I've identified what I believe to be a fairly decent deal for a Nal(Ti) crystal, which is 25mmx25mm.
I'd want to be able to identify isotopes with a fair amount of certainty, but I cannot find any information about how the crystal size affects the reading accuracy, apart from the obvious limitation of isotope size that I can easily sample.

There is a comment on this in the hardware readme: https://github.com/OpenGammaProject/Open-Gamma-Detector/tree/main/hardware#scintillator-cyrstals

In general, try to avoid giant crystal faces with just a single SiPM coupled to it. The optical losses will be quite substantial and you'll probably get worse energy resolution. You can use a 25x25mm crystal no problem, but I'd recommend you get yourself the 2x2 SiPM array board: https://github.com/OpenGammaProject/MicroFC-SiPM-Array-Board

That way you can pretty easily get down to 8% if you assemble everything correctly.

> Would it be simply the case that I may just need to sample my isotope for longer due to the decreased area of the crystal?
Additionally, would discoloration and spots on the crystal affect the results of my gamma spectroscopy much?

Sampling longer always helps, but only to a certain degree. You can't go lower than the intrinsic energy resolution of your entire assembled system. Discoloration can, depending on the extent, significantly reduce the amount of light that reaches the SiPM and therefore also the resolution. However, if there's just a hint of yellow, it'll probably work fine to be honest. You really have to try it if you're unsure. Hope that helps.

**Comment by GhostDog98** [comment]
Awesome, thank you. Just ordered my crystal!

**Comment by NuclearPhoenixx** [comment]
So I've used the 2x2 array a lot, and yes sure the capacitances add up, but all in all I have only seen improved performance. The energy resolution improves by 1-2% or so for a 1x1" compared to just a single 6mm SiPM, and I didn't notice any changes to the range.
